name: CI/CD Workflow

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 and Build with Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: mvn clean install

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 and Run Tests
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: mvn test

  publish:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: sujitkuswain9/technozone-bff
          tags: latest
          registry: docker.io
          dockerfile: ../Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: publish
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: sudo docker pull sujitkuswain9/technozone-bff:latest
      - name: Delete old Docker container
        run: docker rm -f technozone-bff-container || true
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name technozone-bff-container sujitkuswain9/technozone-bff